# Generated by Django 4.1.7 on 2023-04-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_tag',
            field=models.CharField(max_length=128, null=True, verbose_name='Телеграм'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Почта'),
        ),
    ]
