# Generated by Django 4.1.7 on 2023-04-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chat_id',
            field=models.IntegerField(null=True, verbose_name='Номер чата в телеграм'),
        ),
    ]
