# Generated by Django 4.2.1 on 2023-05-08 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_user_chat_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='student_card_id',
            new_name='student_card_number',
        ),
    ]
