# Generated by Django 4.2.1 on 2023-05-08 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_student_card_id_user_student_card_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='chat_id',
            new_name='telegram_chat_number',
        ),
    ]
