# Generated by Django 4.1.7 on 2023-04-24 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_user_chat_id'),
        ('shedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='academic_couple',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shedule.academiccouple'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='group',
            field=models.ManyToManyField(blank=True, to='students.group'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.ManyToManyField(blank=True, to='shedule.subject'),
        ),
    ]
