# Generated by Django 4.1.7 on 2023-04-25 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shedule', '0005_rename_lesson_lesson_lesson_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='lessondate',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата проведения занятия'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='type_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shedule.lessontype'),
        ),
    ]
