# Generated by Django 4.1.7 on 2023-04-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shedule', '0006_lessontype_lessondate_date_lesson_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='weekday',
        ),
        migrations.AddField(
            model_name='lesson',
            name='auditorium',
            field=models.CharField(default='Не назначена', max_length=256),
        ),
    ]
