# Generated by Django 4.2.1 on 2023-05-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_remove_user_lesson'),
        ('shedule', '0007_remove_lesson_weekday_lesson_auditorium'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ManyToManyField(to='personnel.user'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='week',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Первая'), (2, 'Вторая')], default=1),
        ),
    ]
