# Generated by Django 4.2.1 on 2023-05-08 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0005_alter_user_options'),
        ('students', '0005_alter_group_options_alter_user_options_and_more'),
        ('shedule', '0009_alter_lesson_group_alter_lesson_lesson_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academiccouple',
            options={'verbose_name': 'Время занятия', 'verbose_name_plural': 'Время занятий'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Занятие', 'verbose_name_plural': 'Занятия'},
        ),
        migrations.AlterModelOptions(
            name='lessondate',
            options={'verbose_name': 'Дата занятия', 'verbose_name_plural': 'Даты занятий'},
        ),
        migrations.AlterModelOptions(
            name='lessontype',
            options={'verbose_name': 'Тип занятия', 'verbose_name_plural': 'Тип занятий'},
        ),
        migrations.AlterField(
            model_name='academiccouple',
            name='end_time',
            field=models.TimeField(verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='academiccouple',
            name='start_time',
            field=models.TimeField(verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='academic_couple',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shedule.academiccouple', verbose_name='Время занятий'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='auditorium',
            field=models.CharField(default='Не назначена', max_length=256, verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='group',
            field=models.ManyToManyField(to='students.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_date',
            field=models.ManyToManyField(to='shedule.lessondate', verbose_name='Дата занятия'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ManyToManyField(db_index=True, to='personnel.user', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='type_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shedule.lessontype', verbose_name='Тип занятия'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='week',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Первая'), (2, 'Вторая')], default=1, verbose_name='Учебная неделя'),
        ),
        migrations.AlterField(
            model_name='lessontype',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
    ]
